<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="m2ling"
    nsURI="http://m2ling.org/1.0" nsPrefix="m2ling">
  <eSubpackages name="core" nsURI="http://m2ling.org/core/1.0" nsPrefix="core">
    <eClassifiers xsi:type="ecore:EClass" name="EngineType" eSuperTypes="#//core/ConceptItem">
      <eStructuralFeatures xsi:type="ecore:EReference" name="componentTypes" upperBound="-1"
          eType="#//core/ComponentType" eOpposite="#//core/ComponentType/engineType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="subTypes" upperBound="-1"
          eType="#//core/EngineType" containment="true" eOpposite="#//core/EngineType/parent"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//core/EngineType"
          eOpposite="#//core/EngineType/subTypes"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ComponentType" eSuperTypes="#//core/ConceptItem">
      <eStructuralFeatures xsi:type="ecore:EReference" name="subTypes" upperBound="-1"
          eType="#//core/ComponentType" containment="true" eOpposite="#//core/ComponentType/parent"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="engineType" lowerBound="1"
          eType="#//core/EngineType" eOpposite="#//core/EngineType/componentTypes"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//core/ComponentType"
          eOpposite="#//core/ComponentType/subTypes"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Engine" eSuperTypes="#//core/EngineGroup">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="#//core/EngineType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="subEngines" upperBound="-1"
          eType="#//core/Engine" containment="true" eOpposite="#//core/Engine/parent"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
          eType="#//core/Component" eOpposite="#//core/Component/engine"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//core/Engine"
          eOpposite="#//core/Engine/subEngines"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Component" eSuperTypes="#//core/ComponentGroup">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="#//core/ComponentType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="subComponents" upperBound="-1"
          eType="#//core/Component" containment="true" eOpposite="#//core/Component/parent"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="engine" lowerBound="1"
          eType="#//core/Engine" eOpposite="#//core/Engine/components"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//core/Component"
          eOpposite="#//core/Component/subComponents"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ifactor" upperBound="-1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="HasNameAndID" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EngineNode" eSuperTypes="#//core/EngineNodeGroup">
      <eStructuralFeatures xsi:type="ecore:EReference" name="engine" lowerBound="1"
          eType="#//core/Engine"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="subNodes" upperBound="-1"
          eType="#//core/EngineNode" containment="true" eOpposite="#//core/EngineNode/parent"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="componentNodes" upperBound="-1"
          eType="#//core/ComponentNode" eOpposite="#//core/ComponentNode/engineNode"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//core/EngineNode"
          eOpposite="#//core/EngineNode/subNodes"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ComponentNode" eSuperTypes="#//core/ComponentNodeGroup">
      <eStructuralFeatures xsi:type="ecore:EReference" name="component" lowerBound="1"
          eType="#//core/Component"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="engineNode" lowerBound="1"
          eType="#//core/EngineNode" eOpposite="#//core/EngineNode/componentNodes"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="subNodes" upperBound="-1"
          eType="#//core/ComponentNode" containment="true" eOpposite="#//core/ComponentNode/parent"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//core/ComponentNode"
          eOpposite="#//core/ComponentNode/subNodes"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Environnement" eSuperTypes="#//core/RuntimeItem">
      <eStructuralFeatures xsi:type="ecore:EReference" name="componentNodes" upperBound="-1"
          eType="#//core/ComponentNode" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="engineNodes" upperBound="-1"
          eType="#//core/EngineNode" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="componentNodeGroups"
          upperBound="-1" eType="#//core/ComponentNodeGroup" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="engineNodeGroups" upperBound="-1"
          eType="#//core/EngineNodeGroup" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="profile" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ViewPoint" eSuperTypes="#//core/ConceptItem">
      <eStructuralFeatures xsi:type="ecore:EReference" name="componentTypes" upperBound="-1"
          eType="#//core/ComponentType" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="engineTypes" upperBound="-1"
          eType="#//core/EngineType" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ComponentGroup" eSuperTypes="#//core/ArchitectureItem">
      <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
          eType="#//core/Component"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EngineGroup" eSuperTypes="#//core/ArchitectureItem">
      <eStructuralFeatures xsi:type="ecore:EReference" name="engines" upperBound="-1"
          eType="#//core/Engine"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EngineNodeGroup" eSuperTypes="#//core/RuntimeItem">
      <eStructuralFeatures xsi:type="ecore:EReference" name="engineNodes" upperBound="-1"
          eType="#//core/EngineNode"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ComponentNodeGroup" eSuperTypes="#//core/RuntimeItem">
      <eStructuralFeatures xsi:type="ecore:EReference" name="componentNodes" upperBound="-1"
          eType="#//core/ComponentNode"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ArchitectureItem" abstract="true"
        eSuperTypes="#//core/HasNameAndID #//core/HasParameterDefinitions #//core/HasComment #//core/HasTags">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" lowerBound="1"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ConceptItem" abstract="true" eSuperTypes="#//core/HasNameAndID #//core/HasCustomProperties #//core/HasComment #//core/HasTags">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RuntimeItem" abstract="true" eSuperTypes="#//core/HasNameAndID #//core/HasParameterValues #//core/HasComment #//core/HasTags">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Project" eSuperTypes="#//core/ArchitectureItem">
      <eStructuralFeatures xsi:type="ecore:EReference" name="componentsGroups" upperBound="-1"
          eType="#//core/ComponentGroup"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
          eType="#//core/Component"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="engines" upperBound="-1"
          eType="#//core/Engine"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="engineGroups" upperBound="-1"
          eType="#//core/EngineGroup"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="HasTags" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="tags" eType="#//core/Tag"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="tagGroups" lowerBound="1"
          upperBound="-1" eType="#//core/TagGroup"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Tag">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TagGroup">
      <eStructuralFeatures xsi:type="ecore:EReference" name="tags" lowerBound="1"
          upperBound="-1" eType="#//core/Tag"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="HasComment">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="comment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="HasCustomProperties">
      <eStructuralFeatures xsi:type="ecore:EReference" name="customProperties" eType="#//core/CustomProperty"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CustomProperty">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//core/CustomPropertyType"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="CustomPropertyType">
      <eLiterals name="STRING"/>
      <eLiterals name="FLOAT" value="1"/>
      <eLiterals name="INTEGER" value="2"/>
      <eLiterals name="DATE" value="3"/>
      <eLiterals name="BOOLEAN" value="4"/>
      <eLiterals name="TAG_GROUP" value="5"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LinkType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="sourceType" lowerBound="1"
          eType="#//core/ConceptItem"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="destinationType" lowerBound="1"
          eType="#//core/ConceptItem"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Link">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="#//core/LinkType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
          eType="#//core/ArchitectureItem"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="destination" lowerBound="1"
          eType="#//core/ArchitectureItem"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Stream">
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
          eType="#//core/RuntimeItem"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="destination" lowerBound="1"
          eType="#//core/RuntimeItem"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="#//core/Link"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="HasParameterDefinitions" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="HasParameterValues" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="Concern">
      <eStructuralFeatures xsi:type="ecore:EReference" name="viewPoints" upperBound="-1"
          eType="#//core/ViewPoint"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Stakeholder">
      <eStructuralFeatures xsi:type="ecore:EReference" name="concerns" upperBound="-1"
          eType="#//core/Concern"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="projects" upperBound="-1"
          eType="#//core/Project"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="environments" upperBound="-1"
          eType="#//core/Environnement"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="parameters" nsURI="http://m2ling.org/parameters/1.0" nsPrefix="parameters">
    <eClassifiers xsi:type="ecore:EClass" name="ParameterValue" eSuperTypes="#//core/HasComment #//core/HasCustomProperties">
      <eOperations name="getFinalValue"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
          eType="#//core/HasParameterValues"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="definition" lowerBound="1"
          eType="#//parameters/ParameterDefinition"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ParameterDefinition" abstract="true"
        eSuperTypes="#//core/HasComment #//core/HasCustomProperties #//core/HasNameAndID">
      <eOperations name="castParentAsComponent">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Helper method that allows to cast the parent as a component (to be used with component parameter descriptions)&#xD;&#xA;"/>
        </eAnnotations>
      </eOperations>
      <eOperations name="castParentAsEngine">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Helper method that allows to cast the parent as a component (to be used with engine parameter descriptions)"/>
        </eAnnotations>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
          eType="#//core/HasParameterDefinitions"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
          eType="#//parameters/ParameterConstraint" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//parameters/ParameterType"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="exampleValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="derivationExpression"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="overriders" upperBound="-1"
          eType="#//parameters/ParamDefOverrider" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="longDescription" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ParameterConstraint" abstract="true"/>
    <eClassifiers xsi:type="ecore:EEnum" name="ParameterType">
      <eLiterals name="BOOLEAN"/>
      <eLiterals name="DATE" value="1"/>
      <eLiterals name="FLOAT" value="2"/>
      <eLiterals name="INTEGER" value="3"/>
      <eLiterals name="STRING" value="4"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FloatConstraint" eSuperTypes="#//parameters/ParameterConstraint"/>
    <eClassifiers xsi:type="ecore:EClass" name="MinConstraint" eSuperTypes="#//parameters/BoundaryConstraint"/>
    <eClassifiers xsi:type="ecore:EClass" name="BoundaryConstraint" abstract="true"
        eSuperTypes="#//parameters/ParameterConstraint">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="inclusive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="URLConstraint" eSuperTypes="#//parameters/ParameterConstraint"/>
    <eClassifiers xsi:type="ecore:EClass" name="NotNullConstraint" eSuperTypes="#//parameters/ParameterConstraint"/>
    <eClassifiers xsi:type="ecore:EClass" name="RegexpConstraint" eSuperTypes="#//parameters/ParameterConstraint">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="regexp" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OCLConstraint" eSuperTypes="#//parameters/ParameterConstraint">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="expression" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IntegerConstraint" eSuperTypes="#//parameters/ParameterConstraint"/>
    <eClassifiers xsi:type="ecore:EClass" name="MaxConstraint" eSuperTypes="#//parameters/BoundaryConstraint"/>
    <eClassifiers xsi:type="ecore:EClass" name="EMailConstraint" eSuperTypes="#//parameters/ParameterConstraint"/>
    <eClassifiers xsi:type="ecore:EDataType" name="EStructuralFeature" instanceClassName="org.eclipse.emf.ecore.EStructuralFeature"/>
    <eClassifiers xsi:type="ecore:EClass" name="ParamDefOverrider">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="overridedFeature" eType="#//parameters/EStructuralFeature"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="profile" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FormatConstraint" eSuperTypes="#//parameters/ParameterConstraint"/>
  </eSubpackages>
  <eSubpackages name="principles" nsURI="http://m2ling.org/principles/1.0" nsPrefix="principles">
    <eClassifiers xsi:type="ecore:EClass" name="Rule" eSuperTypes="#//core/ConceptItem"/>
  </eSubpackages>
</ecore:EPackage>
