<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="m2ling"
    nsURI="http://m2ling.org/1.0" nsPrefix="m2ling">
  <eSubpackages name="core" nsURI="http://m2ling.org/core/1.0" nsPrefix="core">
    <eClassifiers xsi:type="ecore:EClass" name="ComponentType" eSuperTypes="#//core/ConceptItem">
      <eStructuralFeatures xsi:type="ecore:EReference" name="subTypes" upperBound="-1"
          eType="#//core/ComponentType" containment="true" eOpposite="#//core/ComponentType/parent"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//core/ComponentType"
          eOpposite="#//core/ComponentType/subTypes"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="bindedComponentType"
          eType="#//core/ComponentType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="engineType" eType="#//core/ComponentType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Component" eSuperTypes="#//core/ComponentGroup">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="#//core/ComponentType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="subComponents" upperBound="-1"
          eType="#//core/Component" containment="true" eOpposite="#//core/Component/parent"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//core/Component"
          eOpposite="#//core/Component/subComponents"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="engine" eType="#//core/Component"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="HasNameAndID" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="iD" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          changeable="false" defaultValueLiteral="" iD="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          unsettable="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ComponentNode" eSuperTypes="#//core/ComponentNodeGroup">
      <eStructuralFeatures xsi:type="ecore:EReference" name="component" lowerBound="1"
          eType="#//core/Component"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="subNodes" upperBound="-1"
          eType="#//core/ComponentNode" containment="true" eOpposite="#//core/ComponentNode/parent"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//core/ComponentNode"
          eOpposite="#//core/ComponentNode/subNodes"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="engine" eType="#//core/ComponentNodeGroup"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ViewPoint" eSuperTypes="#//core/ConceptItem #//core/ACResource">
      <eStructuralFeatures xsi:type="ecore:EReference" name="componentTypes" upperBound="-1"
          eType="#//core/ComponentType" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="activities" upperBound="-1"
          eType="#//core/Activity"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="baseViewpoint" eType="#//core/ViewPoint"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ComponentGroup" eSuperTypes="#//core/ArchitectureItem">
      <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
          eType="#//core/Component"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ComponentNodeGroup" eSuperTypes="#//core/RuntimeItem">
      <eStructuralFeatures xsi:type="ecore:EReference" name="componentNodes" upperBound="-1"
          eType="#//core/ComponentNode"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ArchitectureItem" abstract="true"
        eSuperTypes="#//core/HasNameAndID #//core/HasComment #//core/HasTags #//core/HasParameterDefinitions #//core/HasConstraints">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ConceptItem" abstract="true" eSuperTypes="#//core/HasNameAndID #//core/HasCustomProperties #//core/HasComment #//core/HasTags #//core/HasParameterDefinitions #//core/HasConstraints">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RuntimeItem" abstract="true" eSuperTypes="#//core/HasNameAndID #//core/HasComment #//core/HasTags #//core/HasParameterValues #//core/HasConstraints">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="View" eSuperTypes="#//core/ArchitectureItem #//core/ACResource">
      <eStructuralFeatures xsi:type="ecore:EReference" name="componentsGroups" upperBound="-1"
          eType="#//core/ComponentGroup"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
          eType="#//core/Component"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="HasTags" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="tags" upperBound="-1"
          eType="#//core/Tag"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="tagGroups" upperBound="-1"
          eType="#//core/TagGroup"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Tag">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral=""/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TagGroup">
      <eStructuralFeatures xsi:type="ecore:EReference" name="tags" lowerBound="1"
          upperBound="-1" eType="#//core/Tag"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="HasComment"/>
    <eClassifiers xsi:type="ecore:EClass" name="HasCustomProperties">
      <eStructuralFeatures xsi:type="ecore:EReference" name="customProperties" eType="#//core/CustomProperty"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CustomProperty"/>
    <eClassifiers xsi:type="ecore:EEnum" name="CustomPropertyType"/>
    <eClassifiers xsi:type="ecore:EClass" name="LinkType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="sourceType" lowerBound="1"
          eType="#//core/ConceptItem"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="destinationType" lowerBound="1"
          eType="#//core/ConceptItem"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Link">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="#//core/LinkType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
          eType="#//core/ArchitectureItem"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="destination" lowerBound="1"
          eType="#//core/ArchitectureItem"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Stream">
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
          eType="#//core/RuntimeItem"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="destination" lowerBound="1"
          eType="#//core/RuntimeItem"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="#//core/Link"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="HasParameterDefinitions" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="HasParameterValues" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="Stakeholder" eSuperTypes="#//core/HasNameAndID">
      <eStructuralFeatures xsi:type="ecore:EReference" name="views" upperBound="-1"
          eType="#//core/View"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="viewPoints" upperBound="-1"
          eType="#//core/ViewPoint"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="actors" upperBound="-1"
          eType="#//core/Actor" eOpposite="#//core/Actor/stakeholders"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Constraint" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="FloatConstraint" eSuperTypes="#//core/Constraint"/>
    <eClassifiers xsi:type="ecore:EClass" name="MinConstraint" eSuperTypes="#//core/BoundaryConstraint"/>
    <eClassifiers xsi:type="ecore:EClass" name="BoundaryConstraint" abstract="true"
        eSuperTypes="#//core/Constraint">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="inclusive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="URLConstraint" eSuperTypes="#//core/Constraint"/>
    <eClassifiers xsi:type="ecore:EClass" name="NotNullConstraint" eSuperTypes="#//core/Constraint"/>
    <eClassifiers xsi:type="ecore:EClass" name="RegexpConstraint" eSuperTypes="#//core/Constraint">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="regexp" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OCLConstraint" eSuperTypes="#//core/Constraint">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="expression" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IntegerConstraint" eSuperTypes="#//core/Constraint"/>
    <eClassifiers xsi:type="ecore:EClass" name="MaxConstraint" eSuperTypes="#//core/BoundaryConstraint"/>
    <eClassifiers xsi:type="ecore:EClass" name="EMailConstraint" eSuperTypes="#//core/Constraint"/>
    <eClassifiers xsi:type="ecore:EClass" name="FormatConstraint" eSuperTypes="#//core/Constraint"/>
    <eClassifiers xsi:type="ecore:EClass" name="HasConstraints" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="Activity" eSuperTypes="#//core/HasNameAndID">
      <eStructuralFeatures xsi:type="ecore:EReference" name="transitions" upperBound="-1"
          eType="#//core/ActivityTransition"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="responsibles" upperBound="-1"
          eType="#//core/Actor"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="accountables" upperBound="-1"
          eType="#//core/Actor"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="ActivityStatus">
      <eLiterals name="TODO" value="1"/>
      <eLiterals name="CANCELED" literal="CANCELED"/>
      <eLiterals name="VALIDATED" value="2"/>
      <eLiterals name="WAITING_FOR_VALIDATION" value="3"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ActivityTransition" eSuperTypes="#//core/HasComment">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fromStatus" eType="#//core/ActivityStatus"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="toStatus" eType="#//core/ActivityStatus"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OrganisationalUnit" eSuperTypes="#//core/HasComment #//core/HasCustomProperties #//core/HasNameAndID #//core/HasTags"/>
    <eClassifiers xsi:type="ecore:EClass" name="Actor" eSuperTypes="#//core/HasCustomProperties #//core/HasTags">
      <eStructuralFeatures xsi:type="ecore:EReference" name="stakeholders" upperBound="-1"
          eType="#//core/Stakeholder" eOpposite="#//core/Stakeholder/actors"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="unit" lowerBound="1"
          upperBound="-1" eType="#//core/OrganisationalUnit"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="username" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          iD="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="admin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="pwdHash" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ACResource"/>
    <eClassifiers xsi:type="ecore:EEnum" name="AutorizationType">
      <eLiterals name="READ"/>
      <eLiterals name="WRITE" value="1"/>
      <eLiterals name="CREATE" value="2"/>
      <eLiterals name="DELETE" value="3"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Authorization">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//core/AutorizationType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="resource" lowerBound="1"
          eType="#//core/ACResource"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="stakeholders" upperBound="-1"
          eType="#//core/Stakeholder"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="parameters" nsURI="http://m2ling.org/parameters/1.0" nsPrefix="parameters">
    <eClassifiers xsi:type="ecore:EClass" name="ParameterValue" eSuperTypes="#//core/HasComment #//core/HasCustomProperties">
      <eOperations name="getFinalValue"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
          eType="#//core/HasParameterValues"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="definition" lowerBound="1"
          eType="#//parameters/ParameterDefinition"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ParameterDefinition" abstract="true"
        eSuperTypes="#//core/HasComment #//core/HasCustomProperties #//core/HasNameAndID #//core/HasConstraints">
      <eOperations name="castParentAsComponent">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Helper method that allows to cast the parent as a component (to be used with component parameter descriptions)&#xD;&#xA;"/>
        </eAnnotations>
      </eOperations>
      <eOperations name="castParentAsEngine">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Helper method that allows to cast the parent as a component (to be used with engine parameter descriptions)"/>
        </eAnnotations>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
          eType="#//core/HasParameterDefinitions"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
          eType="#//core/Constraint" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//parameters/ParameterType"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="exampleValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="derivationExpression"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="overriders" upperBound="-1"
          eType="#//parameters/ParamDefOverrider" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="longDescription" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="ParameterType">
      <eLiterals name="BOOLEAN"/>
      <eLiterals name="DATE" value="1"/>
      <eLiterals name="FLOAT" value="2"/>
      <eLiterals name="INTEGER" value="3"/>
      <eLiterals name="STRING" value="4"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="EStructuralFeature" instanceClassName="org.eclipse.emf.ecore.EStructuralFeature"/>
    <eClassifiers xsi:type="ecore:EClass" name="ParamDefOverrider">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="overridedFeature" eType="#//parameters/EStructuralFeature"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="environment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="principles" nsURI="http://m2ling.org/principles/1.0" nsPrefix="principles">
    <eClassifiers xsi:type="ecore:EClass" name="Rule" eSuperTypes="#//core/ConceptItem">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="#//principles/RuleStatus"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="priority" eType="#//principles/Priority"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="RuleStatus">
      <eLiterals name="TO_BE_STUDIED"/>
      <eLiterals name="STUDIED" value="1"/>
      <eLiterals name="VALIDATED" value="2"/>
      <eLiterals name="REFUSED" value="3"/>
      <eLiterals name="OBSOLETE" value="4"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="Priority">
      <eLiterals name="VERY_LOW"/>
      <eLiterals name="LOW" value="1"/>
      <eLiterals name="MEDIUM" value="2"/>
      <eLiterals name="HIGH" value="3"/>
      <eLiterals name="VERY_HIGH" value="4"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
