/**
 * Copyright (C) 2012 Bertrand Florat
 *
 * @author "Bertrand Florat <bertrand@florat.net>"
 */
package org.m2ling.presentation;

import com.vaadin.terminal.ThemeResource;
import com.vaadin.ui.Accordion;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Embedded;
import com.vaadin.ui.HorizontalSplitPanel;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.RichTextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

/**
 * 
 */
public class MainFrame extends CustomComponent {

	private static final long serialVersionUID = 569583488180673007L;

	private Accordion accordion;

	/**
	 * @return the accordion
	 */
	public Accordion getAccordion() {
		return accordion;
	}

	private Embedded logo;

	private Panel appPanel;

	private HorizontalSplitPanel splitSidebar;

	private TextField search;

	private RichTextArea comments;

	/**
	 * @return the appPanel
	 */
	public Panel getAppPanel() {
		return appPanel;
	}

	/**
	 * The constructor should first build the main layout, set the composition root and then do any
	 * custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the visual editor.
	 */
	public MainFrame() {
		createComponents();
		buildMenuLayout();
		setSizeFull();
		setCompositionRoot(splitSidebar);
	}

	/**
	 * Create the components to be placed
	 */
	private void createComponents() {
		// Logo
		ThemeResource resLogo = new ThemeResource("img/m2ling_logo.png");
		logo = new Embedded(null, resLogo);

		// App panel
		appPanel = new Panel();
		appPanel.setSizeFull();
		appPanel.addComponent(new Label("m2ling app here !"));

		// Accordion
		accordion = new Accordion();
		accordion.addComponent(new Label("Item1"));
		accordion.setSizeFull();

		// Search box
		search = new TextField("Search");

		// Comments area
		comments = new RichTextArea("Comments");
		comments.setEnabled(false);
		comments.setWidth("100%");
		comments.setHeight("30px");
	}

	/**
	 * Place the components
	 */
	private void buildMenuLayout() {
		// Accordion
		accordion.addTab(comments);
		
		// Sidebar
		VerticalLayout sidebar = new VerticalLayout();
		sidebar.setSpacing(true);
		sidebar.setSizeFull();
		sidebar.addComponent(logo);
		sidebar.addComponent(search);
		sidebar.addComponent(accordion);
		sidebar.setExpandRatio(accordion, 100);
		sidebar.setMargin(true);
		sidebar.setStyleName("sidebar");

		// Sidebar | application
		splitSidebar = new HorizontalSplitPanel();
		splitSidebar.setSplitPosition(20);
		splitSidebar.setSizeFull();
		splitSidebar.addComponent(sidebar);
		splitSidebar.addComponent(appPanel);

	}

}
