/**
 * Copyright (C) 2012 Bertrand Florat
 *
 * @author "Bertrand Florat <bertrand@florat.net>"
 */
package org.m2ling.presentation;

import com.vaadin.terminal.ThemeResource;
import com.vaadin.ui.Accordion;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Embedded;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.HorizontalSplitPanel;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

/**
 * 
 */
public class MainFrame extends CustomComponent {

	private static final long serialVersionUID = 569583488180673007L;

	private Accordion accordion;

	/**
	 * @return the accordion
	 */
	public Accordion getAccordion() {
		return accordion;
	}

	private Embedded logo;

	private Panel appPanel;

	private HorizontalSplitPanel splitSidebar;

	private TextField search;

	/**
	 * @return the appPanel
	 */
	public Panel getAppPanel() {
		return appPanel;
	}

	/**
	 * The constructor should first build the main layout, set the composition root and then do any
	 * custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the visual editor.
	 */
	public MainFrame() {
		createComponents();
		buildMenuLayout();
		setSizeFull();
		setCompositionRoot(splitSidebar);
	}

	/**
	 * Create the components to be placed
	 */
	private void createComponents() {
		// Logo
		ThemeResource resLogo = new ThemeResource("img/m2ling_logo.png");
		logo = new Embedded(null, resLogo);

		// App panel
		appPanel = new Panel();
		appPanel.setSizeFull();
		appPanel.addComponent(new Label("m2ling app here !"));

		// Accordion
		accordion = new Accordion();
		accordion.addComponent(new Label("Item1"));
		accordion.setSizeFull();

		// Search box
		search = new TextField();

	}

	/**
	 * Place the components
	 */
	private void buildMenuLayout() {
		// Search
		HorizontalLayout hlSearch = new HorizontalLayout();
		hlSearch.setSpacing(true);
		hlSearch.addComponent(new Embedded(null, new ThemeResource("img/search_16x16.png")));
		hlSearch.addComponent(search);

		// Sidebar
		VerticalLayout sidebar = new VerticalLayout();
		sidebar.setSpacing(true);
		sidebar.setSizeFull();
		sidebar.addComponent(logo);
		sidebar.addComponent(hlSearch);
		sidebar.addComponent(accordion);
		sidebar.setExpandRatio(accordion, 100);

		// Sidebar | application
		splitSidebar = new HorizontalSplitPanel();
		splitSidebar.setSplitPosition(20);
		splitSidebar.setSizeFull();
		splitSidebar.addComponent(sidebar);
		splitSidebar.addComponent(appPanel);

	}

}
