/**
 * Copyright (C) 2012 Bertrand Florat
 *
 * @author "Bertrand Florat <bertrand@florat.net>"
 */
package org.m2ling.presentation;

import org.m2ling.presentation.i18n.Msg;

import com.google.inject.Inject;
import com.vaadin.terminal.ThemeResource;
import com.vaadin.ui.Accordion;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Embedded;
import com.vaadin.ui.HorizontalSplitPanel;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

/**
 * Mainframe with accordion and application frame
 */
public class MainFrame extends CustomComponent {
	private static final long serialVersionUID = 569583488180673007L;
	private Accordion accordion;
	private Embedded logo;
	private Panel app;
	private HorizontalSplitPanel splitSidebar;
	private TextField search;
	private TextArea comments;
	private final Msg msg;

	/**
	 * The constructor should first build the main layout, set the composition root and then do any
	 * custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the visual editor.
	 */
	@Inject
	public MainFrame(Msg msg) {
		this.msg = msg;
		createComponents();
		buildMenuLayout();
		setSizeFull();
		setCompositionRoot(splitSidebar);
	}

	/**
	 * @return the accordion
	 */
	public Accordion getAccordion() {
		return accordion;
	}

	/**
	 * @return the appPanel
	 */
	public Panel getAppPanel() {
		return app;
	}

	/**
	 * Create the components to be placed
	 */
	private void createComponents() {
		// Logo
		ThemeResource resLogo = new ThemeResource("img/m2ling_logo.png");
		logo = new Embedded(null, resLogo);
		// App panel
		app = new Panel();
		app.setSizeFull();
		// This vertical layout is added automatically at panel creation,
		// it must have an undefined size to allow scrolling
		app.getContent().setHeight("-1");
		// Accordion
		accordion = new Accordion();
		accordion.setSizeFull();
		// Search box
		search = new TextField(msg.get("mf.search"));
		search.setWidth("100%");
		// Comments area
		comments = new TextArea(msg.get("mf.comments"));
		comments.setEnabled(false);
		comments.setWidth("100%");
		comments.setHeight("30px");
	}

	/**
	 * Place the components
	 */
	private void buildMenuLayout() {
		// Accordion
		accordion.addTab(comments);
		// Sidebar
		VerticalLayout sidebar = new VerticalLayout();
		sidebar.setSpacing(true);
		sidebar.setSizeFull();
		sidebar.addComponent(logo);
		sidebar.addComponent(search);
		sidebar.addComponent(accordion);
		sidebar.setExpandRatio(accordion, 100);
		sidebar.setMargin(true);
		sidebar.setStyleName("sidebar");
		// Sidebar | application
		splitSidebar = new HorizontalSplitPanel();
		splitSidebar.setSplitPosition(20);
		splitSidebar.setSizeFull();
		splitSidebar.addComponent(sidebar);
		splitSidebar.addComponent(app);
	}

	public void resetAccordion() {
		accordion.removeAllComponents();
		accordion.addComponent(comments);
	}
}
