<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model"
    nsURI="http://m2lcore/1.0" nsPrefix="m2lcore">
  <eClassifiers xsi:type="ecore:EClass" name="EngineType" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentType" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contains" upperBound="-1"
        eType="#//ComponentType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Engine" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//EngineType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="runs" upperBound="-1" eType="#//Engine"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="runs" upperBound="-1" eType="#//Component"
        eOpposite="#//Component/isRunnedBy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deployedAs" upperBound="-1"
        eType="#//RunningEngine" eOpposite="#//RunningEngine/model"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="isConfigurefBy" eType="#//Parameter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Component" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//ComponentType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contains" upperBound="-1"
        eType="#//Component" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="engineType" lowerBound="1"
        eType="#//EngineType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="isRunnedBy" lowerBound="1"
        eType="#//Engine" eOpposite="#//Engine/runs.1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deployedAs" upperBound="-1"
        eType="#//RunningComponent" eOpposite="#//RunningComponent/model"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="isConfiguredBy" eType="#//Parameter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="keywords" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Architecture" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="engineTypes" upperBound="-1"
        eType="#//EngineType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="System" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="executionEngines" upperBound="-1"
        eType="#//Engine" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="architecture" lowerBound="1"
        eType="#//Architecture"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RunningEngine">
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" lowerBound="1" eType="#//Engine"
        eOpposite="#//Engine/deployedAs"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="runs" upperBound="-1" eType="#//RunningEngine"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="runs" upperBound="-1" eType="#//RunningComponent"
        eOpposite="#//RunningComponent/isRunnedBy"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RunningComponent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contains" upperBound="-1"
        eType="#//RunningComponent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" lowerBound="1" eType="#//Component"
        eOpposite="#//Component/deployedAs"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="isRunnedBy" lowerBound="1"
        eType="#//RunningEngine" eOpposite="#//RunningEngine/runs.1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dependency"/>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="isDerivedFrom" upperBound="-1"
        eType="#//Parameter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owns" upperBound="-1" eType="#//ParameterDescription"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ows" eType="#//ParameterValue"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owns" upperBound="-1" eType="#//ParameterRule"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ows" eType="#//Scope"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterDescription">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contains" upperBound="-1"
        eType="#//ParameterProfile" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterRule"/>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterProfile">
    <eStructuralFeatures xsi:type="ecore:EReference" name="LinkedWith" lowerBound="1"
        eType="#//Parameter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Scope">
    <eStructuralFeatures xsi:type="ecore:EReference" name="maps" upperBound="-1" eType="#//Component"/>
  </eClassifiers>
</ecore:EPackage>
